[aliases]
altair = ["alt"]
connectorx = ["cx"]
cv2 = ["cv"]
"dask.dataframe" = ["dd"]
datetime = ["dt"]
"defusedxml.ElementTree" = ["ET"]
geopandas = ["gpd"]
http = ["http"]
"hypothesis.strategies" = ["st"]
"impala.hiveserver2" = ["hs2"]
"importlib.metadata" = ["md"]
libcst = ["cst"]
logging = ["lg"]
"lxml.etree" = ["ET"]
"matplotlib.pyplot" = ["plt"]
multiprocessing = ["mp"]
narwhals = ["nw"]
niquests = ["http"]
numpy = ["np"]
openpyxl = ["op"]
orjson = ["json"]
pandas = ["pd"]
pandera = ["pa"]
parquet = ["pq"]
pdb = ["dbg"]
"plotly.express" = ["px"]
"plotly.graph_objects" = ["go"]
polars = ["pl"]
pudb = ["dbg"]
pyarrow = ["pa"]
"pyarrow.parquet" = ["pq"]
regex = ["re"]
scipy = ["sp"]
"scipy.stats" = ["ss"]
seaborn = ["sns"]
simplejson = ["json"]
soundfile = ["sf"]
sqlalchemy = ["sa"]
statistics = ["stats"]
"statsmodels.api" = ["sm"]
"statsmodels.formula.api" = ["smf"]
streamlit = ["st"]
structlog = ["sl"]
"structlog.contextvars" = ["cv"]
"structlog.stdlib" = ["log"]
subprocess = ["sp"]
tensorflow = ["tf"]
tigerbeetle = ["tb"]
time = ["tm"]
tomli = ["toml"]
webdataset = ["wds"]
websocket = ["ws"]
xarray = ["xr"]
"xml.etree.ElementTree" = ["ET"]
zstandard = ["zstd"]
