{
  imports = [
    ./browsers.nix
    ./communication.nix
    ./containers.nix
    ./desktop-apps.nix
    ./development.nix
    ./dotfiles.nix
    ./gaming.nix
    ./homepage.nix
    ./i3.nix
    ./keyboard.nix
    ./laptop.nix
    ./media.nix
    ./nvidia-workstation.nix
    ./plasma.nix
    ./selfhosted-apps.nix
    ./terminal.nix
    ./whatpulse.nix
    ./wodan-home.nix
  ];
}
