-- Core: which-key registrations
local ok, wk = pcall(require, "which-key")
if not ok then
	return {}
end

wk.add({
	{ "<leader>w", desc = "Write file" },
	{ "<leader>q", desc = "Quit" },
	{ "<leader>d", group = "debug" },
	{ "<leader>db", desc = "Toggle breakpoint" },
	{ "<leader>dB", desc = "Conditional breakpoint" },
	{ "<leader>dc", desc = "Continue" },
	{ "<leader>di", desc = "Step into" },
	{ "<leader>do", desc = "Step over" },
	{ "<leader>dO", desc = "Step out" },
	{ "<leader>dr", desc = "REPL" },
	{ "<leader>du", desc = "Debug UI" },
	{ "<leader>e", desc = "Reveal in explorer" },
	{ "<leader>f", group = "find" },
	{ "<leader>ff", desc = "Find files" },
	{ "<leader>fg", desc = "Search text" },
	{ "<leader>fs", desc = "Workspace symbols" },
	{ "<leader>fS", desc = "Document symbols" },
	{ "<leader>g", group = "git" },
	{ "<leader>gg", desc = "Neogit" },
	{ "<leader>gD", desc = "Diffview open" },
	{ "<leader>gh", desc = "File history" },
	{ "<leader>t", group = "toggle / test" },
	{ "<leader>tn", desc = "Relative number" },
	{ "<leader><tab>", desc = "Next tab" },
	{ "<leader><S-Tab>", desc = "Previous tab" },
	{ "<leader>tt", desc = "Nearest test" },
	{ "<leader>tf", desc = "File tests" },
	{ "<leader>td", desc = "Debug nearest test" },
	{ "<leader>ts", desc = "Test summary" },
	{ "<leader>to", desc = "Test output" },
	{ "<leader>tO", desc = "Output panel" },
	{ "<leader>tS", desc = "Stop tests" },
	{ "<leader>l", group = "language" },
	{ "<leader>ld", desc = "Line diagnostics" },
	{ "<leader>lq", desc = "Diagnostics to loclist" },
	{ "<leader>lf", desc = "Format buffer" },
	{ "<leader>o", group = "open" },
	{ "<leader>od", desc = "Database UI" },
	{ "<leader>of", desc = "DB buffer" },
	{ "<leader>x", group = "trouble" },
	{ "<leader>xx", desc = "Diagnostics" },
	{ "<leader>xX", desc = "Buffer diagnostics" },
	{ "<leader>xl", desc = "Location list" },
	{ "<leader>xq", desc = "Quickfix list" },
	{ "<leader>xt", desc = "Todo comments" },
	{ "<leader>s", group = "search" },
	{ "<leader>st", desc = "Todo comments" },
	{ "<leader>sn", desc = "Notifications" },
	-- Git (gitsigns) group & mappings
	{ "<leader>h", group = "git (hunks)" },
	{ "<leader>hs", desc = "Stage hunk" },
	{ "<leader>hr", desc = "Reset hunk" },
	{ "<leader>hS", desc = "Stage buffer" },
	{ "<leader>hR", desc = "Reset buffer" },
	{ "<leader>hp", desc = "Preview hunk" },
	{ "<leader>hi", desc = "Preview hunk inline" },
	{ "<leader>hb", desc = "Blame line (full)" },
	{ "<leader>hd", desc = "Diff this" },
	{ "<leader>hD", desc = "Diff vs HEAD~" },
	{ "<leader>hQ", desc = "Quickfix all hunks" },
	{ "<leader>hq", desc = "Quickfix hunks (current)" },
	{ "<leader>hu", desc = "Undo stage hunk" },
	{ "<leader>tb", desc = "Toggle line blame" },
	{ "<leader>tw", desc = "Toggle word diff" },
	-- VS Code-like comment toggle
	{ "<C-_>", desc = "Toggle comment", mode = { "n", "x" } },
})

return {}
