# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# `prev_bg` is a special variable that sets the background color to the previous
# module's background color, which is useful for creating a seamless transition between
# modules. For example, you can use it to create a seamless transition between the
# `directory` and `git_branch` modules.

# You can also override fg and bg colors for each module. `fg:prev_bg fg:light_bg` means
# that the foreground color is the previous module's background color, but if there is
# no previous module, it will be the light_bg color. The same logic applies to the
# background color.

# == current prompt ==
format = """
$python\
$git_branch\
$git_status\
$directory\
$jobs\
$status\
$character\
"""

# == prompt settings ==
# https://starship.rs/config/#prompt
add_newline = false
command_timeout = 500
palette = 'powerline_status'

[palettes.powerline_status]
term_bg = '#121212'
dark_bg = '#303030'
light_bg = '#585858'
pyth = '#26b446' # green
stat = '#d75f00' # orange

# git_status colors
orange = '#ffaf00'
white = '#ffffff'
darkcyan = '#5fafd7'
darkestgreen = '#005f00'
brightgreen = '#afd700'
brightyellow = '#ffd700'
mediumorange = '#d75f00'
darkestred = '#5f0000'
gray0 = '#121212'
gray4 = '#585858'
gray9 = '#bcbcbc'
gray10 = '#d0d0d0'
gray2 = '#303030'
gray8 = '#9e9e9e'
brightred = '#d70000'
mediumpurple = '#875fd7'
brightestorange = '#ffaf00'
darkblue = '#005faf'

# == current prompt settings ==
[python]
style = 'bold fg:white bg:darkcyan'
format = "[ $virtualenv ]($style)"

[git_branch]
style = 'fg:gray9 bg:gray2'
format = """
[ ](fg:prev_bg bg:gray2)\
[$symbol $branch]($style)\
"""
symbol = ''
truncation_length = 12
truncation_symbol = '…'
only_attached = true


# [git_status]
# style = 'bg:dark_bg'
# format = '[ $all_status$ahead_behind ]($style)'

# -    : branch name or commit hash
# - ★   : most recent tag (if enabled)
# - ↓   : n commits behind
# - ↑   : n commits ahead
# - ●   : n staged files
# - ✖   : n unmerged files (conflicts)
# - ✚   : n changed files
# - …   : n untracked files
# - ⚑   : n stashed files

# "gitstatus":                 { "fg": "gray8",           "bg": "gray2", "attrs": [] },
# "gitstatus_branch":          { "fg": "gray8",           "bg": "gray2", "attrs": [] },
# "gitstatus_branch_clean":    { "fg": "green",           "bg": "gray2", "attrs": [] },
# "gitstatus_branch_dirty":    { "fg": "gray8",           "bg": "gray2", "attrs": [] },
# "gitstatus_branch_detached": { "fg": "mediumpurple",    "bg": "gray2", "attrs": [] },
# "gitstatus_behind":          { "fg": "gray10",          "bg": "gray2", "attrs": [] },
# "gitstatus_ahead":           { "fg": "gray10",          "bg": "gray2", "attrs": [] },
# "gitstatus_staged":          { "fg": "green",           "bg": "gray2", "attrs": [] },
# "gitstatus_unmerged":        { "fg": "brightred",       "bg": "gray2", "attrs": [] },
# "gitstatus_changed":         { "fg": "mediumorange",    "bg": "gray2", "attrs": [] },
# "gitstatus_untracked":       { "fg": "brightestorange", "bg": "gray2", "attrs": [] },
# "gitstatus_stashed":         { "fg": "darkblue",        "bg": "gray2", "attrs": [] }

[git_status]
style = 'fg:gray8 bg:prev_bg'
format = """[ \
$behind_count\
$ahead_behind\
$ahead_count\
$staged\
$conflicted\
$modified\
$untracked\
$stashed\
$deleted\
$renamed\
$typechanged\
 ]($style)\
"""
behind = '[↓ ${count}](fg:white bg:prev_bg) '
ahead = '[↑ ${count}](fg:white bg:prev_bg) '
staged = '[● ${count}](fg:green bg:prev_bg) '
conflicted = '[✖ ${count}](fg:brightred bg:prev_bg) '
modified = '[✚ ${count}](fg:mediumorange bg:prev_bg) '
untracked = '[… ${count}](fg:brightestorange bg:prev_bg) '
stashed = '[⚑ ${count}](fg:darkblue bg:prev_bg) '

[directory]
style = 'fg:gray10 bg:gray4'
format = """
[ ](fg:prev_bg bg:gray4)\
[$path]($style)\
[$read_only]($read_only_style)\
"""
truncation_length = 1
# truncation_symbol = '…  '
truncate_to_repo = false
home_symbol = '~'
read_only = ' 󰌾'
use_os_path_sep = true
fish_style_pwd_dir_length = 3
# substitutions break the fish_style_pwd_dir_length setting...
# substitutions = { '/' = '  ' }

[jobs]
format = """
[](fg:mediumorange bg:prev_bg)\
[ $symbol$number]($style)\
"""
style = 'fg:brightyellow bg:mediumorange'
symbol = '⚙ '
threshold = 1
number_threshold = 1

[status]
style = 'fg:brightestorange bg:stat'
format = """
[ ](fg:prev_bg bg:stat)\
[$int ]($style)\
"""
disabled = false

[character]
success_symbol = '[](fg:prev_bg)'
error_symbol = '[](fg:stat)'

# == other settings ==
[time]
disabled = false
time_format = '%R' # Hour:Minute Format
style = 'bg:term_bg'
format = '[$time]($style) '

[os]
style = 'bg:#9A348E'
disabled = true # Disabled by default

[battery]
full_symbol = ':battery:'
charging_symbol = ':zap: '
discharging_symbol = ':skull: '
empty_symbol = ':low_battery: '


[c]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ' '
style = 'bg:#06969A'
format = '[ $symbol $context ]($style)'

[elixir]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[gradle]
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'
symbol = ' '

[haskell]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = '󰆥 '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'bg:#86BBD8'
format = '[ $symbol ($version) ]($style)'

# == symbols ==
[aws]
symbol = '  '

[buf]
symbol = ' '

[cmake]
symbol = ' '

[conda]
symbol = ' '

[crystal]
symbol = ' '

[dart]
symbol = ' '

[fennel]
symbol = ' '

[fossil_branch]
symbol = ' '

[guix_shell]
symbol = ' '

[haxe]
symbol = ' '

[hg_branch]
symbol = ' '

[hostname]
ssh_symbol = ' '

[kotlin]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[meson]
symbol = '󰔷 '

[nix_shell]
symbol = ' '

[ocaml]
symbol = ' '

[os.symbols]
Alpaquita = ' '
Alpine = ' '
AlmaLinux = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CachyOS = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
Nobara = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
RockyLinux = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Void = ' '
Windows = '󰍲 '

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = '󰏗 '

[perl]
symbol = ' '

[php]
symbol = ' '

[pijul_channel]
symbol = ' '

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[swift]
symbol = ' '

[zig]
symbol = ' '
